// Mocks generated by Mockito 5.4.1 from annotations
// in online_bazaar/test/features/admin/presentation/cubit/admin_food_order_cubit_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_bazaar/features/admin/domain/repositories/admin_food_order_repository.dart'
    as _i3;
import 'package:online_bazaar/features/shared/domain/entities/food_order.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFoodOrder_0 extends _i1.SmartFake implements _i2.FoodOrder {
  _FakeFoodOrder_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdminFoodOrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminFoodOrderRepository extends _i1.Mock
    implements _i3.AdminFoodOrderRepository {
  @override
  _i4.Stream<List<_i2.FoodOrder>> getFoodOrders() => (super.noSuchMethod(
        Invocation.method(
          #getFoodOrders,
          [],
        ),
        returnValue: _i4.Stream<List<_i2.FoodOrder>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i2.FoodOrder>>.empty(),
      ) as _i4.Stream<List<_i2.FoodOrder>>);
  @override
  _i4.Future<_i2.FoodOrder> updateFoodOrderStatus(
          _i3.UpdateFoodOrderStatusParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFoodOrderStatus,
          [params],
        ),
        returnValue: _i4.Future<_i2.FoodOrder>.value(_FakeFoodOrder_0(
          this,
          Invocation.method(
            #updateFoodOrderStatus,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.FoodOrder>.value(_FakeFoodOrder_0(
          this,
          Invocation.method(
            #updateFoodOrderStatus,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.FoodOrder>);
  @override
  _i4.Future<void> exportFoodOrdersToSheetFile(
          _i3.ExportFoodOrdersToSheetFileParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportFoodOrdersToSheetFile,
          [params],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
