name: online_bazaar
description: Online Bazaar.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc_test: ^9.1.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.7.1
  csslib: ^1.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  excel: ^2.1.0
  fake_cloud_firestore: ^2.4.1+1
  firebase_auth: ^4.6.1
  firebase_auth_mocks: ^0.12.0
  firebase_core: ^2.13.0
  firebase_remote_config: ^4.2.1
  firebase_storage: ^11.2.1
  firebase_storage_mocks: ^0.6.1
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.0.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_native_splash: ^2.3.0
  flutter_screenutil: ^5.8.1
  font_awesome_flutter: ^10.4.0
  form_builder_validators: ^9.0.0
  get_it: ^7.6.0
  go_router: ^10.2.0
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.0
  mockito: ^5.4.0
  mocktail: ^1.0.0
  responsive_framework: ^1.0.0
  screenshot: ^2.1.0
  sentry_flutter: ^7.6.1
  universal_html: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icons/app_logo.png
  web:
    generate: true
    image_path: assets/icons/app_logo.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/app_logo.png
  android: true
  ios: true
  web: true
