// Mocks generated by Mockito 5.4.1 from annotations
// in online_bazaar/test/features/customer/presentation/cubit/customer_cubit_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_bazaar/features/customer/domain/repositories/customer_repository.dart'
    as _i3;
import 'package:online_bazaar/features/shared/domain/entities/customer.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCustomer_0 extends _i1.SmartFake implements _i2.Customer {
  _FakeCustomer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CustomerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerRepository extends _i1.Mock
    implements _i3.CustomerRepository {
  @override
  _i4.Future<_i2.Customer> setCustomer(_i3.SetCustomerParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCustomer,
          [params],
        ),
        returnValue: _i4.Future<_i2.Customer>.value(_FakeCustomer_0(
          this,
          Invocation.method(
            #setCustomer,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Customer>.value(_FakeCustomer_0(
          this,
          Invocation.method(
            #setCustomer,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Customer>);
}
