// Mocks generated by Mockito 5.4.1 from annotations
// in online_bazaar/test/features/customer/presentation/cubit/customer_cart_cubit_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_bazaar/features/customer/domain/entities/cart.dart'
    as _i2;
import 'package:online_bazaar/features/customer/domain/repositories/customer_cart_repository.dart'
    as _i4;
import 'package:online_bazaar/features/shared/domain/entities/food_order.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCart_0 extends _i1.SmartFake implements _i2.Cart {
  _FakeCart_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFoodOrder_1 extends _i1.SmartFake implements _i3.FoodOrder {
  _FakeFoodOrder_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CustomerCartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerCartRepository extends _i1.Mock
    implements _i4.CustomerCartRepository {
  @override
  _i5.Future<_i2.Cart> setCartCustomer(_i4.SetCartCustomerParams? customer) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCartCustomer,
          [customer],
        ),
        returnValue: _i5.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #setCartCustomer,
            [customer],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #setCartCustomer,
            [customer],
          ),
        )),
      ) as _i5.Future<_i2.Cart>);
  @override
  _i5.Future<_i2.Cart> addCartItem(_i4.AddCartItemParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCartItem,
          [params],
        ),
        returnValue: _i5.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #addCartItem,
            [params],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #addCartItem,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.Cart>);
  @override
  _i5.Future<_i2.Cart> updateCartItem(_i4.UpdateCartItemParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCartItem,
          [params],
        ),
        returnValue: _i5.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #updateCartItem,
            [params],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #updateCartItem,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.Cart>);
  @override
  _i5.Future<_i2.Cart> removeCartItem(_i4.RemoveCartItemParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCartItem,
          [params],
        ),
        returnValue: _i5.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #removeCartItem,
            [params],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #removeCartItem,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.Cart>);
  @override
  _i5.Future<_i2.Cart> validateCart(_i4.ValidateCartParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateCart,
          [params],
        ),
        returnValue: _i5.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #validateCart,
            [params],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #validateCart,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.Cart>);
  @override
  _i5.Future<_i3.FoodOrder> completeCheckout(
          _i4.CompleteCheckoutParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeCheckout,
          [params],
        ),
        returnValue: _i5.Future<_i3.FoodOrder>.value(_FakeFoodOrder_1(
          this,
          Invocation.method(
            #completeCheckout,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.FoodOrder>.value(_FakeFoodOrder_1(
          this,
          Invocation.method(
            #completeCheckout,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.FoodOrder>);
}
